homeassistant: true
mqtt:
  base_topic: ble2mqtt
  server: 'mqtt://127.0.243.243:1883'
controller:
  address: B0:35:9F:CB:5B:1E
  capacity: 6
devices:
  '02:8F:DC:94:01:72':
    type: am43
  '02:94:A3:5F:1D:1D':
    type: am43
